### ISSUE TITLE
Hacking Linux kernel部分make kernel-source出错

### ISSUE THREAD

**Issue by Hanseltu** [tinyclub/rlk4.0#1]
你好，用此环境做笨叔叔实验，在linux-lab目录下执行make kernel-source提示以下信息：
git submodule update --init --remote linux-stable
fatal: unable to access 'https://github.com/tinyclub/linux-stable.git': Could not resolve host:github.com
Unable to fetch in submodule path 'linux-stable'
make: ***[kernel-source] Error 1
另外浏览器网页也无法打开，应该是未连上网络，请问如何解决？

**Comment by lzufalcon** [comment]
@Hanseltu 

你好，可能是访问 github.com 出错，你可以手动执行如下命令下载：

git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git

**Comment by Hanseltu** [comment]
@lzufalcon 
谢谢你，你说的方法可以解决问题。
